name: Build and Publish Extension

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
          
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          run_install: true
        
      - name: Run tests
        run: pnpm unit-test
        
      - name: Package extension
        run: pnpm run package

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: ftl-xml-vsix
          path: "*.vsix"
        
      # - name: Publish to VS Code Marketplace
      #   run: pnpm run publish patch
      #   env:
      #     VSCE_PAT: ${{ secrets.VSCE_PAT }} 